aerogear/aerogear-digger

openshift/README.md, openshift/jenkins-persistent-template.json, openshift/sample-pv.json
Initial version of openshift template
ping @luigizuccarelli
=> AGDIGGER-18 -  openshift template with doc

jenkinsfiles/android_jenkinsfile.groovy
Do android build! KISS!
WIP: It works but things may change. Posting early for feedback.
- Build is scheduled on android jenkins node preconfigured to use new android sdk container. 
(see #6)
- Job with jenkins file needs to created manually for the moment. 
- Job wrapper coming soon in separate PR.
=> AGDIGGER-22 - Android minimal pipeline script

openshift/README.md
@luigizuccarelli wanna give it a quick review ?
=> Adding some notes for Fedora

docker/android-slave/Dockerfile
Image pushed and verified on public cluster.
=> Changed SDK versions

README.md
=> Adding winner meme

README.md, docker/README.md, openshift/README.md
More and more users trying to try this project and in most of the cases they would not require any development setup and have their own openshift instances running somewhere.
I updated documentation and simplified it for QE and product users that would be able now to get this started on openshift clusters they already have. 
quick review @matzew @jgallaso @odra @aliok
=> Adding information about the clients

README.md, admin/README.md, admin/newApiUser.groovy
Allow administrators to script user creation. We can add call to create users later based on this script.
Review @aliok @matzew
=> AGDIGGER-70 - api user script

docker/android-slave/Dockerfile.rhel7, docker/jenkins2-centos/Dockerfile.rhel7
RHEL versions of the dockerfiles.
=> RHMAP-12408 - rhel7 images

admin/README.md, admin/cordova_sandbox.sb
See https://issues.jboss.org/browse/AGDIGGER-83
=> AGDIGGER-83 OSX sandbox definition file for Cordova

admin/cocoapods_sandbox.sb
See https://issues.jboss.org/browse/AGDIGGER-81
Comments in https://github.com/aerogear/digger-jenkins/pull/28 apply here too!
=> AGDIGGER-81 OSX sandbox definition file for CocoaPods

openshift/README.md
Couple of fixes in README. Please comment on particular changes if you disagree or have questions.
=> Fixes in openshift/README.md

openshift/android-sdk-sample-gluster-pv.json, openshift/android-sdk-sample-gluster-pv.yaml, openshift/jenkins-persistent-template.json
**What**
Adding additional templates to create pvs using gluster and nfs
Update the image name and tag for jenkins
=> adding nfs and gluster pv templates

README.md
@matskiv quick review when you have time. Missed this from the last pr to move the openshift templates.
=> add installer link

docker/android-slave/Dockerfile, jenkinsfiles/build.json, jenkinsfiles/cordova_jenkinsfile.groovy
**JIRA**
https://issues.jboss.org/browse/RHMAP-15733
@odra
=> adding build.json template file

jenkinsfiles/build.json
relates to this[ pr ](https://github.com/aerogear/digger-jenkins/pull/51)
fix on path in build.json
@matskiv
=> update keystore path

README.md, jenkinsfiles/README.md
JIRA: https://issues.jboss.org/browse/AGDIGGER-130
cc @laurafitzgerald @odra @wei-lee
=> AGDIGGER-130 Document the mobile app requirements

jenkinsfiles/ios_jenkinsfile.groovy
adds `ENABLE_BITCODE` and `OTHER_CFLAGS` into the correct parameter.
=> using proper flags param

jenkinsfiles/cordova_jenkinsfile.groovy, jenkinsfiles/ios_jenkinsfile.groovy
**JIRA**
https://issues.jboss.org/browse/RHMAP-17067
**Changes**
- adding ios related build steps to the cordova Jenkinsfile
- small language changes to the ios Jenkinsfile
@odra @aliok
=> Rhmap 17067

jenkinsfiles/cordova_jenkinsfile.groovy
small fix around double quotes usage.
=> cordova fixes

admin/create-osx-user.sh
=> adds user to admin group

jenkinsfiles/cordova_jenkinsfile.groovy
=> updated cordova jenkins file

jenkinsfiles/cordova_jenkinsfile.groovy
=> latest cordova jenkinsfile

jenkinsfiles/ios_jenkinsfile.groovy
Uses correct version and short version for ios builds
ping @laurafitzgerald
=> correct ios version

jenkinsfiles/ios_jenkinsfile.groovy
=> correct ios version (#71)

integration/mobileiron/README.md, integration/mobileiron/cloud_uploadapp.sh, integration/mobileiron/core_uploadapp.sh
=> Rhmap 17468

README.md
Gonna resquash, don't mind the number of commits.
=> Document kick start

README.md
Rename Digger Java client repo
=> AGDIGGER-203

README.md
https://issues.jboss.org/browse/AGDIGGER-247
=> added jenkind pub/private key vars to variables

fastlane/README.md
**JIRA**
https://issues.jboss.org/browse/AGDIGGER-213
Relates to [pr](https://github.com/aerogear/aerogear.org/pull/695)
@finp
=> update fastlane instructions

README.md
=> Grammar error in ReadMe.md file
